Vagrant.configure("2") do |config|
  servers = [
    { hostname: "vm1", box: "ubuntu/bionic64", ram: 512, cpu: 1 },
    { hostname: "vm2", box: "ubuntu/bionic64", ram: 512, cpu: 1 },
    { hostname: "vm3", box: "ubuntu/bionic64", ram: 512, cpu: 1 }
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", type: "dhcp"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end
      node.vm.provision "shell" do |s|
        number_of_vms = servers.length
        ssh_pub_key = File.readlines("./id_ed25519_clean.pub").first.strip
        s.inline = <<-SHELL
          echo "#{ssh_pub_key}" >> /home/vagrant/.ssh/authorized_keys
          echo "#{ssh_pub_key}" >> /root/.ssh/authorized_keys
          cp /vagrant/id_ed25519 /home/vagrant/id_ed25519
          chmod 600 /home/vagrant/id_ed25519
          echo "export NUMBER_OF_VMS=#{number_of_vms}" >> /home/vagrant/.bashrc
        SHELL
      end
      node.vm.provision "shell", path: "runner.sh"
    end
  end
end
